// This file will be generated by Supabase CLI
// For now, we'll define basic types manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          phone: string | null
          full_name: string
          avatar_url: string | null
          role: 'customer' | 'shaman' | 'admin'
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          phone?: string | null
          full_name: string
          avatar_url?: string | null
          role: 'customer' | 'shaman' | 'admin'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          phone?: string | null
          full_name?: string
          avatar_url?: string | null
          role?: 'customer' | 'shaman' | 'admin'
          created_at?: string
          updated_at?: string
        }
      }
      // More tables will be added as we implement them
    }
    Views: {}
    Functions: {}
    Enums: {}
  }
}
